FROM node:16-alpine3.14

LABEL version="1.0"
LABEL description="React Frontend for the readiness-challenge-frontend"

WORKDIR /app

COPY ./package.json ./

RUN npm install 

COPY . .

RUN chown -R node:node /app/node_modules

CMD [ "npm", "run", "start" ]
