FROM node:16-alpine3.14

LABEL version="1.0"
LABEL description="React Frontend for the readiness-challenge-frontend"

WORKDIR /app

# COPY ./package.json ./

# RUN npm install 
COPY package.json package-lock.json* ./
RUN npm ci && npm cache clean --force

COPY . .

RUN chown -R node:node /app/node_modules

CMD [ "npm", "run", "start" ]
