version: "3.9"

services:
  backend:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: readiness-challenge-backend
    volumes:
      - /app/node_modules
      # don't overwrite node_modules in container with local node modules
      - ./server:/app
      # this a must for local development so that code changes are reflected real time
      # without the need to rebuild whole image
      # local:container
    ports:
      - 5000:5000
    # local:container
    depends_on:
      # - mongodb
      - cache
    environment:
      NODE_ENV: ${NODE_ENV}
      # MONGO_URI: ${MONGO_URI}
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - library-mern-api

  # mongodb:
  #   container_name: mongo-dev
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  #   volumes:
  #     - mongodb-data:/data/db
  #   networks:
  #     - library-mern-api

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - cache:/data

  # client:
  #   restart: always
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev

  #   container_name: readiness-challenge-frontend
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  #   networks:
  #     - library-mern-api

  # nginx:
  #   restart: always
  #   depends_on:
  #     - backend
  #     - client
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8080:80
  #   networks:
  #     - library-mern-api

networks:
  library-mern-api:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  cache:
    driver: local
