FROM node:16-alpine3.14
LABEL version="1.0"
LABEL description="Development image for the readiness-challenge-backend"
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install && npm cache clean --force

COPY . . 

EXPOSE 5000
CMD ["npm","run","dev"]

