x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ELB}

volumes:
  uploads:
  data:

services:
  rocketchat:
    image: rocket.chat:4.5.0
    volumes:
      - uploads:/app/uploads
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongo:27017/local?replicaSet=rs0
      MONGO_ALT_URL: "mongo"
      ROOT_URL: ${ROOT_URL:-http://localhost}
      PORT: ${PORT:-3000}
    depends_on: [mongo]
    ports:
      - target: ${PORT:-3000}
        published: 3000
        protocol: tcp
        mode: host

  mongo:
    image: bitnami/mongodb:4.4
    command: sudo chown -R 1001 /data
    volumes:
      - data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: "27017"
      MONGODB_INITIAL_PRIMARY_HOST: mongo
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
      MONGODB_ROOT_USER: ${MONGODB_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

networks:
  rocketchatapp:
